### NumPy pkg for multi-dimensional array
#### Vector(1 d)
#### Matrix (2d or 1d)

In [1]:
import numpy as np

In [2]:
list=[6,7,8]


In [3]:
np.array(list)

array([6, 7, 8])

In [5]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
lst=([1,2,3],[4,5,6],[7,8,9])
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [8]:
np.arange(5,38,6)

array([ 5, 11, 17, 23, 29, 35])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [15]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.linspace(1,100,9)

array([  1.   ,  13.375,  25.75 ,  38.125,  50.5  ,  62.875,  75.25 ,
        87.625, 100.   ])

In [20]:
matrix=np.empty((3,3),dtype=int)
matrix

array([[       1,        1,        0],
       [ 6225989,      528,        0],
       [16777984,      487,  7274606]])

In [21]:
matrix_full=np.full((3,3),fill_value=2)
matrix_full

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(N=4,M=5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
np.eye(N=4,M=5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [27]:
np.random.rand(2,4)

array([[0.69463715, 0.364807  , 0.98854282, 0.04141705],
       [0.77992241, 0.21275918, 0.08343678, 0.61937217]])

In [28]:
np.random.randn(2,5)

array([[ 3.44898752,  1.40948358, -0.13258858, -0.06094842,  1.64889438],
       [-0.17080062, -0.00925708, -0.59866116, -0.03363924, -0.87567916]])

In [30]:
np.random.randint(0,10,15)

array([9, 9, 5, 2, 2, 7, 9, 8, 9, 8, 5, 8, 8, 2, 2])

#### arr=np.array([1,2,3,4])

In [33]:
arr.shape

(4,)

In [34]:
arr.size

4

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr.ndim

1

In [37]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [44]:
arr.min()

1

In [45]:
arr.argmin()

0

In [46]:
arr.max()

4

In [47]:
arr.argmax()

3

In [53]:
arr.T

array([1, 2, 3, 4])

In [38]:
array1=np.array([("kani",11),("swas",12),("sow",13)])
array1[0][1]

'11'

In [82]:
sports=np.array(['golf','football','cricket','tennis'])
np.unique(sports)

array(['cricket', 'football', 'golf', 'tennis'], dtype='<U8')

In [40]:
array1.reshape((3,2))

array([['kani', '11'],
       ['swas', '12'],
       ['sow', '13']], dtype='<U11')

In [42]:
array1[0:2][1:]

array([['swas', '12']], dtype='<U11')

In [48]:
array1[3:5]

array([], shape=(0, 2), dtype='<U11')

In [50]:
array1[:2]

array([['kani', '11'],
       ['swas', '12']], dtype='<U11')

#### 2D 

In [51]:
arr1=np.array([(1,2,3),(4,5,6),(7,8,9)])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2=np.array([(11,12,13),(14,15,16),(17,18,19)])
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [67]:
add=arr1+arr2
add

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [68]:
sub=arr1-arr2
sub

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

#### element wise multiplication

In [54]:
pro=arr1*arr2
pro

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

#### matrix multiplication

In [55]:
pro1=arr1.dot(arr2)
pro1

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [56]:
arr1.var()

6.666666666666667

In [57]:
arr1.std()

2.581988897471611

In [79]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [80]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [81]:
np.mean(arr1)

5.0

In [58]:
np.square(arr1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [59]:
np.power(arr1,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [60]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### flatten-turns multi-dimensional array into 1d

In [62]:
np.ndarray.flatten(arr2)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [63]:
for i in arr1:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [64]:
for i in arr2:
    print(i)

[11 12 13]
[14 15 16]
[17 18 19]


In [66]:
for i in arr2:
    for j in i:
      print(j)

11
12
13
14
15
16
17
18
19


In [69]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr1[1:2,0:2]

array([[4, 5]])

In [74]:
arr1[1:,:2]

array([[4, 5],
       [7, 8]])

In [75]:
arr1[2][2]

9

In [76]:
arr1[1][2]

6

In [77]:
arr1[:,2]

array([3, 6, 9])

In [78]:
arr1[0:2,1:2]

array([[2],
       [5]])

In [85]:
matrix_1=np.full((10),fill_value=0)
matrix_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
matrix_1=np.full((10),fill_value=0)
matrix_1[5]=1
matrix_1

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])